/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.michaeldydean.passwordgeratorma;

//import javax.swing.JOptionPane;
import java.awt.Toolkit;
import processadortexto.ModificadorTexto;
import processadortexto.ValidadorDeTexto;

/**
 * -Projeto: Gerador de Senha
 * -Tipo: JFrame
 * -Descrição: É a janela principal do programa, nela é possível criar senhas fortes
 * e elaboradas para uso distintos. Através de palavras ou parâmetros definidos para
 * a elaboração da senha é criada uma senha totalmente aleatória ou não. No caso
 * de senhas elaboradas de acordo com uma dada palavra, o software defini algumas
 * letras(caracteres) que seram susbstituindo por outras com semelhança, criando 
 * assim uma senha fácil de ser memorizada.
 *
 * @author Michael Dydean
 *
 * @version 1.0
 */
/*
 Criado em 18-01-16.
 Atualizado em 19-01-16.
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInformarPrimeiroCaracteres = new javax.swing.JTextField();
        jComboBoxDefinirPrimeiroCaracteres = new javax.swing.JComboBox<>();
        jTextFieldInformarUltimoCaracteres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDefinirUltimoCaracteres = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxQtdCaracteres = new javax.swing.JComboBox<>();
        jComboBoxDefinirDemaisCaracteres = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonGerar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneSenha1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldPalavra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneSenha2 = new javax.swing.JTextPane();
        jButtonGerar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de Senhas");
        setResizable(false);

        jTabbedPane.setFocusable(false);

        jLabel1.setText("Definir Tipo do Primeiro Caractere:");

        jLabel2.setText("Informar Primeiro Caractere:");

        jComboBoxDefinirPrimeiroCaracteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeros", "Letras Maiúsculas", "Letras Minúsculas", "Outros" }));

        jLabel3.setText("Informar  Último Caractere:");

        jComboBoxDefinirUltimoCaracteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeros", "Letras Maiúsculas", "Letras Minúsculas", "Outros" }));

        jLabel4.setText("Definir Tipo do Último Caractere:");

        jLabel5.setText("Quantidade de Caracteres:");

        jComboBoxQtdCaracteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "6", "8", "12", "16" }));

        jComboBoxDefinirDemaisCaracteres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numeros", "Letras Maiúsculas", "Letras Minúsculas", "Outros" }));

        jLabel6.setText("Definir Tipo dos Demais Caracteres:");

        jButtonGerar1.setText("Gerar Senha");
        jButtonGerar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerar1ActionPerformed(evt);
            }
        });

        jTextPaneSenha1.setBackground(new java.awt.Color(255, 255, 204));
        jTextPaneSenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTextPaneSenha1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxQtdCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxDefinirDemaisCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxDefinirUltimoCaracteres, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDefinirPrimeiroCaracteres, 0, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldInformarUltimoCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldInformarPrimeiroCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButtonGerar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldInformarPrimeiroCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDefinirPrimeiroCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldInformarUltimoCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDefinirUltimoCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxQtdCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxDefinirDemaisCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonGerar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Definir Parâmetros para Senha", jPanel1);

        jLabel7.setText("Informe  a Palavra:");

        jTextPaneSenha2.setBackground(new java.awt.Color(255, 255, 204));
        jTextPaneSenha2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextPaneSenha2);

        jButtonGerar2.setText("Gerar Senha");
        jButtonGerar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTextFieldPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButtonGerar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButtonGerar2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane.addTab("Utilizar Palavra Base para Senha", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * O método responde ao evento do botão gerar senha da primeira aba. Ao se acionado
     * O método gera a senha através dos método caractere de extremidade e centrais, 
     * após isso, a senha será exibida no painel de texto.
     * 
     * @see ValidadorDeTexto
     * 
     * @param evt 
     */
    private void jButtonGerar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerar1ActionPerformed

        int indice1 = jComboBoxDefinirPrimeiroCaracteres.getSelectedIndex();
        int indice2 = jComboBoxDefinirUltimoCaracteres.getSelectedIndex();

        String senha = "" + caractereDeExtremidade(jTextFieldInformarPrimeiroCaracteres.getText(), indice1);
        senha += caractereDeCentrais();
        senha += caractereDeExtremidade(jTextFieldInformarUltimoCaracteres.getText(), indice2);

        ValidadorDeTexto validador = new ValidadorDeTexto(senha);

        validador.tamanhoExato(Integer.parseInt("" + jComboBoxQtdCaracteres.getSelectedItem()));

        //if(validador.isValidado()) {
        jTextPaneSenha1.setText(senha);
//        } else {
//             JOptionPane.showMessageDialog(null, "Defina corretamente os parâmetros", "Aviso", 2);
//        }

    }//GEN-LAST:event_jButtonGerar1ActionPerformed

    /**
     * O método responde ao evento gerado pelo botão gerar senha da segunda aba. 
     * Ao ser acionado, o processo de substituição de caracteres é implementado e 
     * exibido no painel de texto.
     * 
     * @param evt 
     */
    private void jButtonGerar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerar2ActionPerformed
        jTextPaneSenha2.setText(substituiCaracteres(jTextFieldPalavra.getText()));
    }//GEN-LAST:event_jButtonGerar2ActionPerformed

    /**
     * O método faz a substituição de caracteres por outros caracteres semelhantes ou
     * com formato aparentemente igual.
     * 
     * @param texto
     * @return 
     */
    String substituiCaracteres(String texto) {

        int tamanhoTexto = texto.length();

        ModificadorTexto mod = new ModificadorTexto(texto);

//        for(int i = 0; i < tamanhoTexto; i++) {
//            
//            char letra = texto.charAt(i);
//            
//            if('a') {
//                ModificadorTexto mod = new ModificadorTexto();
        mod.transformarCaractere('a', '@');
        mod.transformarCaractere('b', '6');
        mod.transformarCaractere('B', '8');
        mod.transformarCaractere('C', '(');
        mod.transformarCaractere('d', 'D');
        mod.transformarCaractere('e', '&');
        mod.transformarCaractere('E', '&');
        mod.transformarCaractere('F', 'f');
        mod.transformarCaractere('f', 'F');
        mod.transformarCaractere('g', 'G');
        mod.transformarCaractere('G', 'g');
        mod.transformarCaractere('H', 'h');
        mod.transformarCaractere('h', 'H');
        mod.transformarCaractere('I', '1');
        mod.transformarCaractere('l', '|');
        mod.transformarCaractere('L', '!');
        mod.transformarCaractere('J', ')');
        mod.transformarCaractere('n', 'N');
        mod.transformarCaractere('q', '9');
        mod.transformarCaractere('t', 'T');
        mod.transformarCaractere(' ', '_');
        mod.transformarCaractere(',', '-');
        mod.transformarCaractere('s', '5');
        mod.transformarCaractere('S', '$');
        mod.transformarCaractere('o', '0');
        mod.transformarCaractere('O', '0');
        mod.transformarCaractere('u', 'U');
        mod.transformarCaractere('U', 'u');
        mod.transformarCaractere('x', '%');
        mod.transformarCaractere('z', 'Z');
        mod.transformarCaractere('Z', 'z');
//            }
//            
        // }

        return mod.getTexto();
    }

    /**
     * O método define o primeiro ou último caractere, sendo ele aleatórios de acordo
     * com o tipo definido pelo usuário ou especificado, iserindo o caractere no campo
     * de texto da interface.
     * 
     * @param qtdCaracteres
     * @return 
     */
    String caractereDeExtremidade(String texto, int indice) {

        String caractere = texto;
        String caractereAleatorio;

        processadortexto.ValidadorDeTexto validador = new ValidadorDeTexto(caractere);

        validador.tamanhoMinimoMaximo(1, 1);

        switch (indice) {
            case 0:
                validador.setTipoTexto("\\d");
                caractereAleatorio = caracteresAleatoriosNumeros(1);
                break;
            case 1:
                validador.setTipoTexto("\\w");
                caractereAleatorio = caracteresAleatoriosLetras(1).toUpperCase();
                break;
            case 2:
                caractereAleatorio = caracteresAleatoriosLetras(1);
                validador.setTipoTexto("\\w");
                break;
            default:
                caractereAleatorio = caracteresAleatoriosOutros(1);
                break;
        }

//        if (validador.isValidado() == false) {
//            JOptionPane.showMessageDialog(null, "Insira no campo de texto apenas um caractere e de acordo com o tipo definido.", "Aviso", 2);
//        } 
        if (caractere.length() > 0) {
            return caractere;
        } else {
            return caractereAleatorio;
        }
    }

    /**
     * O método forma o texto entre o primeiro e último caractere, formando-o com
     * caracteres aleatórios de tipo definido pelo usuário.
     * 
     * @param qtdCaracteres
     * @return 
     */
    String caractereDeCentrais() {

        int qtdCarateres = Integer.parseInt(jComboBoxQtdCaracteres.getSelectedItem().toString());
        int indice = jComboBoxDefinirDemaisCaracteres.getSelectedIndex();
        String caractereAleatorio;

        qtdCarateres -= 2;

        switch (indice) {
            case 0:
                caractereAleatorio = caracteresAleatoriosNumeros(qtdCarateres);
                break;
            case 1:
                caractereAleatorio = caracteresAleatoriosLetras(qtdCarateres).toUpperCase();
                break;
            case 2:
                caractereAleatorio = caracteresAleatoriosLetras(qtdCarateres);
                break;
            default:
                caractereAleatorio = caracteresAleatoriosOutros(qtdCarateres);
                break;
        }

        return caractereAleatorio;

    }

    /**
     * O método gera texto composto por caracteres do tipo numérico.
     * 
     * @param qtdCaracteres
     * @return 
     */
    private String caracteresAleatoriosNumeros(int qtdCaracteres) {

        String txtGerado = "";
        int numero;

        for (int i = 0; i < qtdCaracteres; i++) {

            numero = (int) ((int) (Math.random() * 10));

            txtGerado += numero;

        }

        return txtGerado;
    }

    /**
     * O método gera texto composto por caracteres do tipo letra.
     * 
     * @param qtdCaracteres
     * @return 
     */
    private String caracteresAleatoriosLetras(int qtdCaracteres) {

        String lista = "qwertuiopasdfghjklzxcvbnmça";

        String txtGerado = "";
        int numero;

        for (int i = 0; i < qtdCaracteres; i++) {

            numero = (int) ((int) 1 + (Math.random() * 26));

            txtGerado += lista.charAt(numero);

        }

        return txtGerado;
    }

    /**
     * O método gera texto composto por caracteres do tipo símbolo e específicos.
     * 
     * @param qtdCaracteres
     * @return 
     */
    private String caracteresAleatoriosOutros(int qtdCaracteres) {

        String lista = "'!@#$%¨&*()_-+=?´[]~;.,|<>:}{`?@";

        String txtGerado = "";
        int numero;

        for (int i = 0; i < qtdCaracteres; i++) {

            numero = (int) ((int) 1 + (Math.random() * 31));

            txtGerado += lista.charAt(numero);

        }

        return txtGerado;
    }
    
     /**
     * O método inseri um icone na janela principal do software.
     *
     * @see Toolkit
     */
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("icone.png"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerar1;
    private javax.swing.JButton jButtonGerar2;
    private javax.swing.JComboBox<String> jComboBoxDefinirDemaisCaracteres;
    private javax.swing.JComboBox<String> jComboBoxDefinirPrimeiroCaracteres;
    private javax.swing.JComboBox<String> jComboBoxDefinirUltimoCaracteres;
    private javax.swing.JComboBox<String> jComboBoxQtdCaracteres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldInformarPrimeiroCaracteres;
    private javax.swing.JTextField jTextFieldInformarUltimoCaracteres;
    private javax.swing.JTextField jTextFieldPalavra;
    private javax.swing.JTextPane jTextPaneSenha1;
    private javax.swing.JTextPane jTextPaneSenha2;
    // End of variables declaration//GEN-END:variables

}
